### ISSUE TITLE
TypeError: Cannot read property 'children' of undefined when execute .getPlaylist()

### ISSUE THREAD

**Issue by WildEgor** [alexandrucancescu/node-vlc-client#3]
TypeError: Cannot read property 'children' of undefined
    at Function.parsePlaylistEntries (....\node_modules\vlc-client\dist\Client.js:570:13)

**Comment by WildEgor** [comment]
Probably, it because I call this in event emitter.

**Comment by WildEgor** [comment]
It causes response object has c.name in language differ from 'Playlist'

**Comment by alexandrucancescu** [comment]
> It causes response object has c.name in language differ from 'Playlist'

I don't understand what you mean
