### ISSUE TITLE
add how to use guide

### ISSUE THREAD

**Issue by akshatdalton** [alexandrucancescu/node-vlc-client#5]
Hi, can you please basic guide that how to use this library?
I was getting the following error irrespective of whatever command I run:
```
Uncaught Error: Request error | Code 404 | Message Not Found
```
How I tried to run it:
```.js
const VLC = require("vlc-client");

const vlc = new VLC.Client({
    ip: "localhost",
    port: 8080,
    username: "steve_aoki", //username is optional
    password: "edm"
});

await vlc.playFile("<path_to_the_file>");
```
The very last line throws the above error.

**Comment by mtbossa** [comment]
> Hi, can you please basic guide that how to use this library? I was getting the following error irrespective of whatever command I run:
> 
> ```
> Uncaught Error: Request error | Code 404 | Message Not Found
> ```
> 
> How I tried to run it:
> 
> ```js
> const VLC = require("vlc-client");
> 
> const vlc = new VLC.Client({
>     ip: "localhost",
>     port: 8080,
>     username: "steve_aoki", //username is optional
>     password: "edm"
> });
> 
> await vlc.playFile("<path_to_the_file>");
> ```
> 
> The very last line throws the above error.

Are you already serving the VLC HTTP server?

**Comment by akshatdalton** [comment]
> Are you already serving the VLC HTTP server?

Yeah, I got the idea that what we need to do after checking out your tests. Got the idea that how to start VLC HTTP server using other libraries.
